name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: python -m pytest

  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: tests
    env:
      GCP_PROJECT: python-todo-app-454322
      GCP_REGION: us-central1
      IMAGE: gcr.io/python-todo-app-454322/python-todo-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT }}

      - name: Build Docker image using Cloud Build
        run: |
          gcloud builds submit --tag $IMAGE .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy python-todo-app \
            --image $IMAGE \
            --platform managed \
            --region $GCP_REGION \
            --allow-unauthenticated \
            --quiet \
            --verbosity=debug
