name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT: python-todo-app-454322
      GCP_REGION: us-central1
      IMAGE: gcr.io/python-todo-app-454322/python-todo-app

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SERVICE_KEY }}
        export_default_credentials: true

    - name: Build Docker image using Cloud Build
      run: |
        gcloud builds submit --tag $IMAGE .

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy python-todo-app \
          --image $IMAGE \
          --platform managed \
          --region $GCP_REGION \
          --allow-unauthenticated \
          --quiet
